version: "3"
services:
  httpd:
    privileged: true
    build: "."
    image: www/httpd
    container_name: apache2
    ports:
      - "80:80"
    tty: true
    volumes:
      - .:/var/www/localhost/htdocs
    networks:
      - backend
    links:
      - mysql
  mysql:
    image: mysql:5.7.30
    container_name: mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=eventura
      - MYSQL_PASSWORD=0102
      - MYSQL_ROOT_PASSWORD=0102
      - MYSQL_DATABASE=default_schem
    volumes:
      - ~/mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 0102
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    ports:
      - 8181:80
    networks:
      - backend
networks:
  backend:
